---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: fedora/k8s-regional
  name: subscription
spec:
  channel: ramen-demos/channel
  placement:
    placementRef:
      kind: Placement
      name: placement
