# Kustomization for OpenShift Regional DR environment.
---
resources:
  - ../base
patches:
  - target:
      kind: VirtualMachine
      name: centos-stream
    patch: |-
      - op: add
        path: /spec/template/spec/domain/devices/interfaces/0/masquerade
        value: {}
  # Use internal ceph cluster.
  - target:
      kind: PersistentVolumeClaim
      name: centos-stream
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd-virtualization
  - target:
      kind: PersistentVolumeClaim
      name: additional-disk
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: ocs-storagecluster-ceph-rbd-virtualization