---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: additional-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: STORAGE_CLASS_NAME
  volumeMode: Block
